### PR TITLE
MethodCZT

### PR DESCRIPTION
**Pull request by Jonas1225**

### CODE REVIEW

**Comment by Jonas1225** [comment]
Dear Prof. Heintzmann,
I studied ZoomedPupilProp.m in the psftoolbox-matlab and, based on Julia's functions, wrote the methodCZT. It allows for arbitrary input of zoom depth, size of the zoomed pupil, and czt zoom scale. It runs well and smoothly according to my current understanding after a whole week of testing and debugging. I have gained a better understanding of FFT and CZT and find this Julia package very interesting.

Question: In runtest.jl, the command @test ctr_test(a_czt, a_RW, 0.1) fails, and I have no idea why.

Sincerely,
Shuxuan Jiang
7/1/2024

＃Master’s Research Work in the Field of "Generation of Point-Spread Functions for Advanced Imaging Microscopy in Julia"＃
Compare_MethodTime
zoomdepth10
p_RW, p_shell, p_CZT, p_iter
test

**Comment by Jonas1225** [comment]
apsf image using MethodCZT with zoom depth = 10
zoomdepth10

**Comment by Jonas1225** [comment]
apsf image using MethodCZT with zoom depth = 1
plot_1

**Comment by Jonas1225** [comment]
apsf image using MethodCZT with zoom depth = 1
zDepth1

**Comment by Jonas1225** [comment]
btw: I shouldn't upload util.jl.  I withdraw this file from the public request.

**Comment by RainerHeintzmann** [comment]
Thanks for the examples. 
Note sure what is shown there. Can you please tell what the rows in figure 1 mean?
If they all show the same PSF parameters, then something is wrong there. The slope of the cones should all match.

**Comment by Jonas1225** [comment]
p_RW, p_shell, p_CZT for zdepth = 10 , p_iter 
plot_5

**Comment by Jonas1225** [comment]
p_RW, p_shell, p_CZT for z depth = 1, p_iter
p_RW, p_shell, p_CZT for z depth = 10, p_iter
p_RW, p_shell, p_CZT for z depth = 15, p_iter




I understand what you mean, I will check for the problem of  xz plane slope of cones.

**Comment by RainerHeintzmann** [comment]
... Why do you have to select a "zoom-depth"? Also the asymmetry for the CZT results is worrying.

**Comment by RainerHeintzmann** [comment]
... the method should not have any different arguments than the standard methods. No first extra argument needed! Also it should not need the `zDepth` argument.

**Comment by RainerHeintzmann** [comment]
... comparisons should be done in XZ to `MethodRichardsWolf `, `MethodSincR` or `MethodPropagateIterative`. `MethodPropagate` and `MethodShell` are expected to have wrap-around problems.

**Comment by Jonas1225** [comment]
Okay, I will consider all and then give a feedback.

**Comment by Jonas1225** [comment]
"Why do you have to select a "zoom-depth"? Also the asymmetry for the CZT results is worrying."
ans: I realise that problem. I did not correctly understand ZDepth and ZDist in this formula: Propagator = exp(-1i*kz*ZDist). I thought they are different during propagation. I will correct it in the function.

**Pull request closed without merging**
