### PR TITLE
Modifed CZT method

### PR DESCRIPTION
**Pull request by Jonas1225**
Dear Porfessor Heintzmann,
I met problem during converting matlab code to julia code  about method CZT. I modified many times but fail to achieve expectation. I don't know where the problem lies in my julia code. I need your help. Dina Ratsimandresy (CC) didn't answer me. The matlab code is in attachment. I make a pull request about my julia code. Hope you can help me find the problem in my julia code.
Regards 
Shuxuan Jiang

### CODE REVIEW

**Comment by Jonas1225** [comment]
[matlab.txt](https://github.com/user-attachments/files/16426007/matlab.txt)

**Comment by Jonas1225** [comment]
plot_czt
plot_czt

**Comment by Jonas1225** [comment]
@test ctr_test(a_czt, a_RW, 0.1)   always fails and I can do nothing about it with my own knowledge

**Comment by Jonas1225** [comment]
Dina Ratsimandresy reply to me. I will try to make improvement in my julia code.

**Comment by RainerHeintzmann** [comment]
Let me know, if you need any help. Also, if you send images like the one above, you need to give me some context. I have no ideas what these figures are and whether they are correct or not. I do see some asymmeteries in panels 4 and 6, but I dont know what these are.

**Pull request closed without merging**
