### PR TITLE
Modification-for-MethodCZT

### PR DESCRIPTION
**Pull request by Jonas1225**

### CODE REVIEW

**Comment by Jonas1225** [comment]
Dear Prof. Heintzmann,
due to an insufficient understanding of zDepth earlier, I spent some time troubleshooting. Now the images appear quite normal. I adjusted the zoom depth to 5, 10, and 15 micrometers, respectively, and obtained the corresponding PSF amplitude images for CZT. As the depth increases, the Fourier wrap-around problem is avoided, while the computation time also increases.

The current issue is that runtest.jl still reports an error for @test ctr_test(a_czt, a_RW, 0.1). I understand that this test compares the central part of the apsf calculated by MethodRichardsWolf and MethodCZT. If the two images are different, an error is triggered, but I don't know why they differ.
I suspect the issue lies in the last column of Figure 6. In the lateral plane of the apsf in the standard method, there is a long black line in the middle, which is not present in my MethodCZT. I think the problem might be with the iczt() in my code, but I don't know how to fix it.

The first three images are the MethodCZT apsf images for zoom depths of 5, 10, and 15, respectively. The fourth image is the error terminal, and the fifth and sixth show the comparison between MethodRichardsWolf and MethodCZT in (32, 32, 32) and (128, 128, 128).
Best 
Shuxuan Jiang
＃Master’s Research Work in the Field of "Generation of Point-Spread Functions for Advanced Imaging Microscopy in Julia"＃

**Comment by Jonas1225** [comment]
zDepth5
zDepth10
zDepth10

**Comment by Jonas1225** [comment]
error

**Comment by Jonas1225** [comment]
a_czt a_RW_crop
a_czt a_RW_full

**Comment by Jonas1225** [comment]
The vertical black line is very noticeable in the comparison of the last column of (32, 32, 32).
a_czt a_RW_crop

**Comment by Jonas1225** [comment]
If you're very busy, although I can't figure out why at the moment, I'll just think it through and solve it myself in this week.
Best

**Comment by Jonas1225** [comment]
I have identified the issue.  I suspect the problem likely lies in a bug within the existing inverse_czt() function in FourierTools.jl. I observed that the images obtained by applying iczt and ift2d to the propagated pupil differ significantly. Consequently, the test @test ctr_test(a_czt, a_RW, 0.1) fails.

The images below compare a cropped 32x32 section (from a 128x128 image) produced by iczt(ZoomedPupils, c_4dim) and ift2d(ZoomedPupils). There is a noticeable discrepancy, with the iczt image showing a blurred area along the diagonal in the third column. I need your confirmation and guidance to determine if there is indeed an issue with the existing iczt() function.
inverse CZT
ift2d

**Comment by Jonas1225** [comment]
If you are too busy, I will check this week whether there is a bug in iczt(). My judgment is based on the fact that the amplitude fields obtained by the slice-propagated pupils through inverse czt and inverse fft2d, respectively, are quite different.

**Comment by RainerHeintzmann** [comment]
> I have identified the issue. I suspect the problem likely lies in a bug within the existing inverse_czt() function in FourierTools.jl. I observed that the images obtained by applying iczt and ift2d to the propagated pupil differ significantly. Consequently, the test @test ctr_test(a_czt, a_RW, 0.1) fails.
> 
> The images below compare a cropped 32x32 section (from a 128x128 image) produced by iczt(ZoomedPupils, c_4dim) and ift2d(ZoomedPupils). There is a noticeable discrepancy, with the iczt image showing a blurred area along the diagonal in the third column. I need your confirmation and guidance to determine if there is indeed an issue with the existing iczt() function. inverse CZT ift2d


I do not understand what you mean.
I did a quick check and did not see any issues with iczt() compared to ift2d():
```julia
julia> a = rand(ComplexF64, 11,10)
11×10 Matrix{ComplexF64}:
 0.0288438+0.192957im   0.840345+0.362158im  0.0565897+0.369052im  …     0.783512+0.270091im   0.273394+0.919281im
  0.913364+0.739158im   0.706905+0.647545im   0.226647+0.558347im         0.22835+0.48452im     0.48083+0.794505im
  0.979501+0.431037im    0.34647+0.127111im    0.67946+0.659129im        0.462377+0.906172im   0.869757+0.369371im
  0.575172+0.426217im   0.440913+0.110391im  0.0205283+0.968254im        0.768394+0.0941143im  0.198147+0.0195409im
   0.81942+0.244876im   0.668839+0.239796im   0.930352+0.180756im     0.000438026+0.817548im   0.883271+0.853509im
  0.314531+0.280454im   0.107389+0.11272im    0.298078+0.038989im  …     0.657595+0.535704im   0.766831+0.367995im
  0.722099+0.106107im  0.0108911+0.981963im   0.524419+0.371314im        0.388372+0.939905im   0.776854+0.97159im
  0.233329+0.878592im   0.915602+0.358595im   0.640753+0.521962im       0.0697877+0.241258im   0.912205+0.0183993im
  0.153112+0.727988im  0.0887556+0.7615im     0.320045+0.680532im        0.435481+0.587783im   0.821336+0.401008im
  0.486034+0.127198im    0.70214+0.671445im   0.374602+0.191929im        0.782208+0.284669im   0.182799+0.346821im
  0.141181+0.400625im   0.723542+0.508391im   0.117766+0.61826im   …     0.258806+0.950541im   0.619015+0.11838im

julia> maximum(abs.(iczt(a,(1,1)) .- ift2d(a)))
1.7422013638940487e-15
```
If you find something which you think is wrong, please always directly provide a minimum working example (MWE).
Thist should ideally look like my example above and not call lots of nested functions.

**Comment by RainerHeintzmann** [comment]
I just looked at the code. I think some things are fundamentally wrong here.
The idea of the CZT approach, as far as I remember is that 
1. The pupil is filled to the available size sz_0  corresponding to the required pixels in the central focal field, the zoom compensates for the "too big pupil" which was calculated. This reduces errors.
2. With these settings there is a certain depth up to which the propagation can still deal with this over-sampled pupil. For this limit depth an equation can be derived.
3. From this depth on a bigger size sz_1 is used (e.g. ~30% more along X and Y), a new zoomed pupil is calculated and new propagated pupils are calculated until the next limit is hit (same equation as above). The difference here is that the czt() or iczt() should now have a different input and output size (i.e. number of pixels along X and Y).

This is repeated until the stack is filled.

It precludes to use a sinlge 3D stack of pupils, since such a stack is only good for a bunch of planes. 
However in lines 105-110 you allways use the same `ZoomedPupil` and never recalculate the pupil for a larger grid. This seems not a very good choice. 
The above value of 30% can be a configurable parameter, but the default should be such that the best speed is achieved.
If too small, it will be slow since the pupil has to be recalculated in every slice. If too large, it is slow, since the arrays are larger than needed in the calculation.

**Comment by Jonas1225** [comment]
Dear Prof. Heintzmann,
Thank you for your guidance. You are an expert in Julia. I have learned a lot. I will make the modifications and reply as soon as possible.
Shuxuan Jiang

**Pull request closed without merging**
